# Tester ProTN package

```{r load functions, warning=F, message=FALSE}
setwd("/home/gabriele/Desktop/UNITN/proTN_package/")
lapply(list.files("./R", pattern = ".R", full.names = T), function(x){if(!file.info(x)$isdir){source(x)}})

# Package requided
library(data.table)
library(readxl)
library(stringi)
library(ggplot2)
library(DEqMS)
library(proBatch)
library(writexl)
library(ggrepel)
library(ggbeeswarm)
library(limma)
```


## Test proteomics pipeline

```{r read_proteomics}
proteome_data <- read_proteomics(software = "MQ", folder = "./data/case_study_proteomics/case_study_1/", peptide_filename = "evidence")
```


```{r preprocess_figure}
generate_abundance <- generate_abundance_plot(proteome_data = proteome_data)
generate_abundance

generate_peptide_distribution <- generate_peptide_distribution_plot(proteome_data = proteome_data)
generate_peptide_distribution
```
# Test impute function
```{r impute_function}
imputed_data <- impute_intensity(proteome_data = proteome_data)
imputed_data
```

# Test normalization
```{r normalization_function}
normalized_data <- normalization_ProTN(proteome_data = imputed_data)
normalized_data
```

# Test Batch Correction -- NOT TESTED YET
```{r batch_function, eval=FALSE}
# TODO: NEED TO TEST
batch_coor_data <- normalization_ProTN(proteome_data = normalized_data, batch_col = "batch")
batch_coor_data
```

# Test Exporter
```{r batch_function, eval=FALSE}
save_abundance_tables(proteome_data = normalized_data)
```

# Test figure distribution normalized
```{r normalized_plot}
prot_plot <- plot_abundance_distribution(proteome_data = normalized_data, type = "protein")
prot_plot
pep_plot <- plot_abundance_distribution(proteome_data = normalized_data, type = "peptide")
pep_plot
```

# MDS AND PCA
```{r mds_normalized}
prot_mds <- mds_plot(proteome_data = normalized_data, type = "protein")
prot_mds
pep_mds <- mds_plot(proteome_data = normalized_data, type = "peptide")
pep_mds
```

```{r pca_normalized}
prot_mds <- pca_plot(proteome_data = normalized_data, type = "protein")
prot_mds
pep_mds <- pca_plot(proteome_data = normalized_data, type = "peptide")
pep_mds
```

# List protein boxplot
```{r boxplot_protein}
prot_boxplot <- plot_selected_proteins(proteome_data = normalized_data, list_protein = c("Aaas","Aacs"))
prot_boxplot
```


# Differential analysis
```{r differential_analysis}
formule_contrast <- list("A2016vsWT"="A2016T-wt")

differential_results <- differential_analysis(proteome_data = normalized_data, formule_contrast = formule_contrast, 
                                              fc_thr=0.75, pval_fdr = "p_val", pval_thr=0.05, signal_thr=0)

differential_results

# TODO: prepare exporter differential analysis
# chunk: diff_analysis
```




