#'  Function to save protein and peptide tables
#'
#' @param proteome_data Object proTN
#' @details \strong{ProTN}
#' @examples 
#' ## ## Example:
#' ## example
#' ## example2
#' @import data.table
#' @export
save_abundance_tables <- function(proteome_data, dirOutput="results_ProTN", subfolder="table") {
  message("Saving abundance tables...")
  
  c_anno <- copy(proteome_data$c_anno)
  # Process proteins
  expr_mat <- copy(proteome_data$dat_gene)
  setnames(expr_mat, "GeneName", "gene")
  expr_l_df <- melt(expr_mat, id.vars = "gene", variable.name = "sample", value.name = "expr")
  expr_l_df <- expr_l_df[c_anno, on = "sample"]
  expr_cond_df <- expr_l_df[, .(N = .N, avg = mean(expr), sd = sd(expr), CV = sd(expr) / mean(expr), se = sd(expr) / sqrt(.N)), by = .(condition, gene)]
  
  expr_avg_df <- dcast(expr_cond_df[, .(gene, condition, avg)], gene ~ condition, value.var = "avg")
  colnames(expr_avg_df)[-1] <- paste0(colnames(expr_avg_df)[-1], "_avg")
  expr_se_df <- dcast(expr_cond_df[, .(gene, condition, se)], gene ~ condition, value.var = "se")
  colnames(expr_se_df)[-1] <- paste0(colnames(expr_se_df)[-1], "_se")
  expr_cv_df <- dcast(expr_cond_df[, .(gene, condition, CV)], gene ~ condition, value.var = "CV")
  colnames(expr_cv_df)[-1] <- paste0(colnames(expr_cv_df)[-1], "_Coef_Variant_(%)")
  
  expr_avgse_df <- Reduce(merge, list(expr_avg_df, expr_se_df, expr_cv_df))
  colnames(expr_avgse_df)[1] <- "GeneName"
  
  # Merge peptide information
  n_pep_prot <- unique(merge.data.table(as.data.table(proteome_data$psm_peptide_table[, .(Accession, Description, GeneName)]), 
                                        as.data.table(proteome_data$psm_anno_df)[, .(Num.Peptide = .N), by = symbol], 
                                        by.x = "GeneName", by.y = "symbol"))

  df_to_save <- list(
    "protein_per_sample" = merge.data.table(n_pep_prot, expr_mat, by.x = "GeneName", by.y = "gene"),
    "protein_per_condition" = merge.data.table(n_pep_prot, expr_avgse_df, by = "GeneName")
  )
  
  # Process peptides
  expr_mat <- copy(proteome_data$dat_pep)
  expr_l_df <- melt(expr_mat, id.vars = "ID_peptide", variable.name = "sample", value.name = "expr")
  expr_l_df <- expr_l_df[c_anno, on = "sample"]
  expr_cond_df <- expr_l_df[, .(N = .N, avg = mean(expr), sd = sd(expr), CV = sd(expr) / mean(expr), se = sd(expr) / sqrt(.N)), by = .(condition, ID_peptide)]
  
  expr_avg_pep_df <- dcast(expr_cond_df[, .(ID_peptide, condition, avg)], ID_peptide ~ condition, value.var = "avg")
  colnames(expr_avg_pep_df)[-1] <- paste0(colnames(expr_avg_pep_df)[-1], "_avg")
  expr_se_pep_df <- dcast(expr_cond_df[, .(ID_peptide, condition, se)], ID_peptide ~ condition, value.var = "se")
  colnames(expr_se_pep_df)[-1] <- paste0(colnames(expr_se_pep_df)[-1], "_se")
  expr_cv_pep_df <- dcast(expr_cond_df[, .(ID_peptide, condition, CV)], ID_peptide ~ condition, value.var = "CV")
  colnames(expr_cv_pep_df)[-1] <- paste0(colnames(expr_cv_pep_df)[-1], "_Coef_Variant_(%)")
  
  expr_avgse_pep_df <- Reduce(merge, list(expr_avg_pep_df, expr_se_pep_df, expr_cv_pep_df))
  
  # Prepare README
  readme_sheet <- data.frame("INFO" = c(NA, "Excel file containing abundance values generated by proTN.", 
                                        "Abundances are log2 transformed, normalized, imputed (and batch corrected).",
                                        "Sheet *protein_per_sample*: protein abundances per sample.",
                                        "Sheet *peptide_per_sample*: peptide abundances per sample.",
                                        "Sheet *protein_per_condition*: protein abundances per condition.",
                                        "Sheet *peptide_per_condition*: peptide abundances per condition."))
  
  df_to_save <- list(
    "README" = readme_sheet,
    "protein_per_sample" = df_to_save$protein_per_sample,
    "peptide_per_sample" = merge(proteome_data$psm_peptide_table, proteome_data$dat_pep, by = "ID_peptide"),
    "protein_per_condition" = df_to_save$protein_per_condition,
    "peptide_per_condition" = merge.data.table(proteome_data$psm_peptide_table, expr_avgse_pep_df, by = "ID_peptide")
  )
  
  if(!dir.exists(dirOutput)){
    message(paste0("Creating dir: ",dirOutput))
    dir.create(dirOutput)
  }
  if(!is_null(subfolder)){
    if(!dir.exists(paste0(dirOutput, "/", subfolder))){
      message(paste0("Creating dir: ",dirOutput, "/", subfolder))
      dir.create(paste0(dirOutput, "/", subfolder))
    }
    writexl::write_xlsx(df_to_save, paste0(dirOutput,"/", subfolder, "/normalised_abundances.xlsx"))
  } else{
    writexl::write_xlsx(df_to_save, paste0(dirOutput, "/normalised_abundances.xlsx"))
  }
  
  message("Abundance tables saved successfully.")
}
