#' Save Abundance Tables for Proteomics Data
#'
#' This function processes proteomics and phosphoproteomics data to compute summary statistics and save the results in an Excel file. It includes normalized, imputed, and batch-corrected abundance values for proteins and peptides, per sample and per condition.
#'
#' @param proteome_data List; a list containing proteomics or phosphoproteomics data.
#' @param dirOutput Character; the directory path where the results should be saved. Default is "results_ProTN".
#' @param subfolder Character; a subfolder within `dirOutput` where the results will be stored. Default is "table".
#'
#' @import data.table
#' @import writexl
#' @export
save_abundance_tables <- function(proteome_data, dirOutput="results_ProTN", subfolder="table") {
  message("Saving abundance tables...")
  phospho_with_proteome = FALSE
  if(("c_anno" %in% names(proteome_data))){
    c_anno <- copy(proteome_data$c_anno)
  } else if(("c_anno_proteome" %in% names(proteome_data)) & ("c_anno_phospho" %in% names(proteome_data))){
    c_anno <- copy(proteome_data$c_anno_proteome)
    phospho_with_proteome = TRUE
  } else{
    stop("Missing sample annotation!")
  }
  # Process proteins
  expr_mat <- copy(proteome_data$dat_gene)
  setnames(expr_mat, "GeneName", "gene")
  expr_l_df <- melt(expr_mat, id.vars = "gene", variable.name = "sample", value.name = "expr")
  expr_l_df <- expr_l_df[c_anno, on = "sample"]
  expr_cond_df <- expr_l_df[, .(N = .N, avg = mean(expr), sd = sd(expr), CV = sd(expr) / mean(expr), se = sd(expr) / sqrt(.N)), by = .(condition, gene)]
  
  expr_avg_df <- dcast(expr_cond_df[, .(gene, condition, avg)], gene ~ condition, value.var = "avg")
  colnames(expr_avg_df)[-1] <- paste0(colnames(expr_avg_df)[-1], "_avg")
  expr_se_df <- dcast(expr_cond_df[, .(gene, condition, se)], gene ~ condition, value.var = "se")
  colnames(expr_se_df)[-1] <- paste0(colnames(expr_se_df)[-1], "_se")
  expr_cv_df <- dcast(expr_cond_df[, .(gene, condition, CV)], gene ~ condition, value.var = "CV")
  colnames(expr_cv_df)[-1] <- paste0(colnames(expr_cv_df)[-1], "_Coef_Variant_(%)")
  
  expr_avgse_df <- Reduce(merge, list(expr_avg_df, expr_se_df, expr_cv_df))
  colnames(expr_avgse_df)[1] <- "GeneName"
  
  # Merge peptide information
  n_pep_prot <- unique(merge.data.table(as.data.table(proteome_data$psm_peptide_table[, .(Accession, Description, GeneName)]), 
                                        as.data.table(proteome_data$psm_anno_df)[, .(Num.Peptide = .N), by = symbol], 
                                        by.x = "GeneName", by.y = "symbol"))

  df_to_save <- list(
    "protein_per_sample" = merge.data.table(n_pep_prot, expr_mat, by.x = "GeneName", by.y = "gene"),
    "protein_per_condition" = merge.data.table(n_pep_prot, expr_avgse_df, by = "GeneName")
  )
  
  # Process peptides
  if(("c_anno" %in% names(proteome_data))){
    c_anno <- copy(proteome_data$c_anno)
  } else if(("c_anno_proteome" %in% names(proteome_data)) & ("c_anno_phospho" %in% names(proteome_data))){
    c_anno <- copy(proteome_data$c_anno_phospho)
  } else{
    stop("Missing sample annotation!")
  }
  expr_mat <- copy(proteome_data$dat_pep)
  expr_l_df <- melt(expr_mat, id.vars = "ID_peptide", variable.name = "sample", value.name = "expr")
  expr_l_df <- expr_l_df[c_anno, on = "sample"]
  expr_cond_df <- expr_l_df[, .(N = .N, avg = mean(expr), sd = sd(expr), CV = sd(expr) / mean(expr), se = sd(expr) / sqrt(.N)), by = .(condition, ID_peptide)]
  
  expr_avg_pep_df <- dcast(expr_cond_df[, .(ID_peptide, condition, avg)], ID_peptide ~ condition, value.var = "avg")
  colnames(expr_avg_pep_df)[-1] <- paste0(colnames(expr_avg_pep_df)[-1], "_avg")
  expr_se_pep_df <- dcast(expr_cond_df[, .(ID_peptide, condition, se)], ID_peptide ~ condition, value.var = "se")
  colnames(expr_se_pep_df)[-1] <- paste0(colnames(expr_se_pep_df)[-1], "_se")
  expr_cv_pep_df <- dcast(expr_cond_df[, .(ID_peptide, condition, CV)], ID_peptide ~ condition, value.var = "CV")
  colnames(expr_cv_pep_df)[-1] <- paste0(colnames(expr_cv_pep_df)[-1], "_Coef_Variant_(%)")
  
  expr_avgse_pep_df <- Reduce(merge, list(expr_avg_pep_df, expr_se_pep_df, expr_cv_pep_df))
  
  # Prepare README
  if(phospho_with_proteome){
    readme_sheet <- data.frame("INFO"=c(NA,
                                        "Excel file containing abundance values generated by proTN.",
                                        "Abundances are log2 transformed, normalized, imputed (and batch corrected).",
                                        "Sheet *protein_per_sample*: protein abundances per sample. (PROTEOME)",
                                        "Sheet *peptide_per_sample*: peptide abundances per sample. (PHOSPHO-PROTEOME)",
                                        "Sheet *protein_per_condition*: protein abundances per condition (average & standard deviation), as defined in the Sample Annotation. (PROTEOME)",
                                        "Sheet *peptide_per_condition*: peptide abundances per condition (average & standard deviation), as defined in the Sample Annotation. (PHOSPHO-PROTEOME)"
    ))
  } else{
    readme_sheet <- data.frame("INFO" = c(NA, "Excel file containing abundance values generated by proTN.", 
                                          "Abundances are log2 transformed, normalized, imputed (and batch corrected).",
                                          "Sheet *protein_per_sample*: protein abundances per sample.",
                                          "Sheet *peptide_per_sample*: peptide abundances per sample.",
                                          "Sheet *protein_per_condition*: protein abundances per condition.",
                                          "Sheet *peptide_per_condition*: peptide abundances per condition."))
  }
  
  
  df_to_save <- list(
    "README" = readme_sheet,
    "protein_per_sample" = df_to_save$protein_per_sample,
    "peptide_per_sample" = merge(proteome_data$psm_peptide_table, proteome_data$dat_pep, by = "ID_peptide"),
    "protein_per_condition" = df_to_save$protein_per_condition,
    "peptide_per_condition" = merge.data.table(proteome_data$psm_peptide_table, expr_avgse_pep_df, by = "ID_peptide")
  )
  
  if(!dir.exists(dirOutput)){
    message(paste0("Creating dir: ",dirOutput))
    dir.create(dirOutput)
  }
  if(!is.null(subfolder)){
    if(!dir.exists(paste0(dirOutput, "/", subfolder))){
      message(paste0("Creating dir: ",dirOutput, "/", subfolder))
      dir.create(paste0(dirOutput, "/", subfolder))
    }
    write_xlsx(df_to_save, paste0(dirOutput,"/", subfolder, "/normalised_abundances.xlsx"))
  } else{
    write_xlsx(df_to_save, paste0(dirOutput, "/normalised_abundances.xlsx"))
  }
  
  message("Abundance tables saved successfully.")
}

#' Save Differential Analysis Results to Excel
#'
#' This function saves the results of a differential analysis (proteomics or phospho-proteomics)
#' into an Excel file. It merges the results with the sample annotation data and generates a
#' comprehensive Excel file with the analysis results, including protein and peptide-level
#' differential expression data.
#'
#' @param proteome_data A list containing proteomic data.
#' @param differential_results A list containing differential expression results.
#' @param dirOutput The directory where the results file will be saved. Default is "results_ProTN".
#' @param subfolder The subfolder within `dirOutput` where the file will be saved. Default is "table".
#' @param phospho_ctrl A logical flag to indicate if phospho control data should be excluded.
#'   Default is `FALSE`.
#'
#' @import writexl
#' @importFrom dplyr left_join inner_join group_by summarize_all
#'
#' @examples
#' \dontrun{
#' save_differential_analysis_table(proteome_data = proteome_data_example,
#'                                  differential_results = differential_results_example,
#'                                  dirOutput = "results_directory")
#' }
#' @export
save_differential_analysis_table <- function(proteome_data, differential_results, 
                                             dirOutput="results_ProTN", subfolder="table",
                                             phospho_ctrl = FALSE){
  if(("c_anno" %in% names(proteome_data))){
    phospho_with_proteome = FALSE
  } else if(("c_anno_phospho" %in% names(proteome_data))){
    phospho_with_proteome = TRUE
  } else{
    stop("Missing sample annotation!")
  }
  
  if(phospho_with_proteome){
    psm_peptide_table <- copy(proteome_data$psm_peptide_table)
    toPrint_pep<-copy(differential_results$peptide_results_wide)
    if(!phospho_ctrl){
      colToKeep <- grep("_Phospho_CTRL", names(toPrint_pep), value = T, invert = T)
      toPrint_pep <- toPrint_pep[, ..colToKeep]
    }
    
    readme_sheet <- data.frame("INFO"=c(NA,
                                        "Excel file containing the results of differential analysis, according to the contrasts defined in the Design file.",
                                        NA,
                                        "Annotation columns:",
                                        "1. *Accession*: protein UniprotID,",
                                        "2. *Description*: protein description,",
                                        "3. *GeneName*: Gene Symbol,",
                                        "4. *Peptide_Sequence*: peptide sequence,",
                                        "5. *Peptide_Modifications*: peptide modifications,",
                                        "6. *Peptide_Position*: start and end position of the peptide within the protein sequence, defined UniprotID,",
                                        NA,
                                        "And for each comparison:",
                                        "8. *class*: defined according to the fold change, p-value and abundance thresholds specified in the input: \"+\" up-regulated protein/peptide, \"-\" down-regulated protein/peptide, \"=\" invariant protein/peptide",
                                        "9. *log2_FC*: protein/peptide log2 transformed fold change",
                                        "10. *FC*: protein/peptide fold change",
                                        "11. *p_val*: protein/peptide contrast p-value",
                                        "12. *p_adj*: protein/peptide adjusted p-value (FDR after BH correction)"
    ))
    
    #Export table with SE e MEAN
    peptide_DE <- inner_join(psm_peptide_table, toPrint_pep, by=c("ID_peptide" = "id"))
    colnames(peptide_DE)[1:8] <- c("Accession","Description","GeneName","Peptide_Sequence","Peptide_Modifications","Phosphorylation_percentage","ID_Peptide","Peptide_Tryptic")
    df_to_save<-list("README"=readme_sheet,
                     "peptide_DE"=peptide_DE)
  } else{
    psm_peptide_table <- copy(proteome_data$psm_peptide_table)
    toPrint<-copy(differential_results$protein_results_wide)
    colnames(toPrint)[1]<-"GeneSymbol"
    toPrint_pep<-copy(differential_results$peptide_results_wide)
    
    readme_sheet <- data.frame("INFO"=c(NA,
                                        "Excel file containing the results of differential analysis, according to the contrasts defined in the Design file. The file is organized in the following sheets:",
                                        "protein_DE: protein differential expression results protein abundances per sample.",
                                        "peptide_DE: peptide differential expression results. ",
                                        NA,
                                        "Annotation columns:",
                                        "1. *Accession*: protein UniprotID,",
                                        "2. *Description*: protein description,",
                                        "3. *GeneName*: Gene Symbol,",
                                        "4. *Peptide_Sequence*: peptide sequence,",
                                        "5. *Peptide_Modifications*: peptide modifications,",
                                        "6. *Peptide_Position*: start and end position of the peptide within the protein sequence, defined UniprotID,",
                                        "7. *Peptide_Tryptic*: peptide tryptic digestion status (fully tryptic, N-semi tryptic, C-semi tryptic, non tryptic)",
                                        NA,
                                        "And for each comparison:",
                                        "8. *class*: defined according to the fold change, p-value and abundance thresholds specified in the input: \"+\" up-regulated protein/peptide, \"-\" down-regulated protein/peptide, \"=\" invariant protein/peptide",
                                        "9. *log2_FC*: protein/peptide log2 transformed fold change",
                                        "10. *FC*: protein/peptide fold change",
                                        "11. *p_val*: protein/peptide contrast p-value",
                                        "12. *p_adj*: protein/peptide adjusted p-value (FDR after BH correction)"
    ))
    
    #Export table with SE e MEAN
    prot_id <- unique(psm_peptide_table[,c("Accession","GeneName")]) %>% group_by(GeneName) %>% summarize_all(toString) %>% left_join(unique(psm_peptide_table[,c("Accession","Description","GeneName")]), 
                                                                                                                                      by = "GeneName", 
                                                                                                                                      multiple = "first",
                                                                                                                                      suffix = c(".id", ".old"))
    protein_DE <- unique(left_join(prot_id[,c("Accession.id","Description","GeneName")], toPrint, by=c("GeneName" = "GeneSymbol")))
    colnames(protein_DE)[1:3] <- c("Accession","Description","GeneName")
    peptide_DE <- left_join(psm_peptide_table, toPrint_pep, by=c("ID_peptide" = "id"))[,-c(1)]
    colnames(peptide_DE)[1:7] <- c("Accession","Description","GeneName","Peptide_Sequence","Peptide_Modifications","ID_Peptide","Peptide_Tryptic")
    df_to_save<-list("README"=readme_sheet,
                     "protein_DE"=protein_DE,
                     "peptide_DE"=peptide_DE)
  }

  if(!dir.exists(dirOutput)){
    message(paste0("Creating dir: ",dirOutput))
    dir.create(dirOutput)
  }
  if(!is.null(subfolder)){
    if(!dir.exists(paste0(dirOutput, "/", subfolder))){
      message(paste0("Creating dir: ",dirOutput, "/", subfolder))
      dir.create(paste0(dirOutput, "/", subfolder))
    }
    write_xlsx(df_to_save, paste0(dirOutput,"/", subfolder, "/differential_expression.xlsx"))
  } else{
    write_xlsx(df_to_save, paste0(dirOutput, "/differential_expression.xlsx"))
  }
  
}
